import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from './components/navigation/navigation';
import Footer from "./components/footer/footer";


import 'leaflet/dist/leaflet.css';
import { Suspense } from "react";
import Loader from "./components/loader/loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hardestee Driving School",
  description: "Generated by create next app",
  icons:{
    icon:"/hardestree logo.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<Loader />}>
          <Navigation />
            {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
